#!/usr/bin/env bash
# Install and Config HAproxy on lb-01 server


# Install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
frontend lindagift
    bind *:80
    default_backend lindagift

backend lindagift
    balance roundrobin
    server 154501-web-01 54.234.79.208:80 check
    server 154501-web-02 100.25.2.197:80 check
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/g' etc/default/haproxy

sudo service haproxy restart
