#!/usr/bin/env bash
# Installs and configure HAproxy on the lb-01 server
# using roundrobin algorithm

sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure HAProxy using roundrobin algorithm
echo "
frontend lindagift_front
        bind *:80
        default_backend lindagift_backa

backend lindagift_back
        balance roundrobin
        server 154501-web-01 54.234.79.208:80 check
        server 154501-web-02 100.25.2.197:80 check
">> /etc/haproxy/haproxy.cfg

# Enable HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
